version: '3.8'

services:
  # Servicio de base de datos para usuarios
  mysql-users:
    image: mysql:5.7
    container_name: mysql-users
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: users_db
    ports:
      - "3307:3306"
    networks:
      - microservices-network
    volumes:
      - mysql-users-data:/var/lib/mysql

  # Servicio de base de datos para productos
  mysql-products:
    image: mysql:5.7
    container_name: mysql-products
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: products_db
    ports:
      - "3308:3306"
    networks:
      - microservices-network
    volumes:
      - mysql-products-data:/var/lib/mysql

  # Microservicio de usuarios
  users-service:
    build: ./users-service
    container_name: users-service
    environment:
      - MYSQL_HOST=mysql-users
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root_password
      - MYSQL_DATABASE=users_db
    ports:
      - "3001:3001"
    networks:
      - microservices-network
    depends_on:
      - mysql-users

  # Microservicio de productos
  products-service:
    build: ./products-service
    container_name: products-service
    environment:
      - MYSQL_HOST=mysql-products
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root_password
      - MYSQL_DATABASE=products_db
    ports:
      - "3002:3002"
    networks:
      - microservices-network
    depends_on:
      - mysql-products

  # API Gateway
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "3000:3000"
    networks:
      - microservices-network
    depends_on:
      - users-service
      - products-service

networks:
  microservices-network:
    driver: bridge

volumes:
  mysql-users-data:
  mysql-products-data:
